# Generated by Django 5.0.3 on 2024-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_actors_movie_director_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, to='movies.director'),
        ),
    ]
